glib: adaptions for libmbim
1. glib: don't assume GNU libiconv

   This removes the glib config switch that made the build assume a GNU libiconv
   which led to the following compile error:

   ! .../lib/glib/glib/gconvert.c:55:2: error: #error GNU libiconv in use but
   !   included iconv.h not from libiconv

2. glib: fix "no such instruction" in symbol file

   This changes several 'R' entries to 'T' entries in the glib symbols file that
   caused assemble errors as follows:

   ! glib.symbols.s:1621: Error: no such instruction: `glib_binary_age R'
   ! glib.symbols.s:1625: Error: no such instruction: `glib_interface_age R'
   ! glib.symbols.s:1626: Error: no such instruction: `glib_major_version R'
   ! glib.symbols.s:1628: Error: no such instruction: `glib_micro_version R'
   ! glib.symbols.s:1629: Error: no such instruction: `glib_minor_version R'

3, glib: adapt run script

   - Remove obsolete pthread.lib.so boot module as it is now part of
    libc.lib.so.

   - Provide '/tmp' directory as a g_file_open_tmp test wants to create
     a file in there.

   - Use [depot_user] for selecting depot archives instead of hardcoding
     it to 'genodelabs'.

4. glib: enable gobject and gio subsystem

   - Provide proper definitions for 32 and 64-bit machines
   - Add gobject and gio subsystems
   - Depends on libffi, which is currently only availabe for arm_v7a and
    x86_64.

   The 'glib' symbols file contains pretty much all symbols, even if the
   belong to supported or rather not supported backends, e.g. dbus.

by mstein and cnuke

Ref #168 and #223